POST http://localhost:8081/api/auth/sign-up
Content-Type: application/json

{
    "user_email": "test@gmail.com",
    "user_password": "password123"
}

###
GET http://localhost:8081/api/auth/verify

###

POST http://localhost:8081/api/auth/sign-out

###
POST http://localhost:8081/api/auth/sign-in
Content-Type: application/json

{
    "user_email": "test@gmail.com",
    "user_password": "password123"
}